---
- name: install PHP packages
  yum: pkg={{ item }} state=installed
  with_items:
    - php
    - php-common
    - php-xml
    - php-mysql
    - php-gd
    - php-tidy
    - php-pear
    - php-mbstring
    - php-devel
    - php-pecl-apc
    - php-pecl-memcache

- name: set php_ini location for pear
  shell: pear config-set php_ini /etc/php.ini

- name: set php_ini location for pecl
  shell: pecl config-set php_ini /etc/php.ini

- name: copy php.ini
  template: src=php.ini dest=/etc/php.ini
  notify:
    - restart apache

- name:  uploadprogress | test uploadprogress exists
  command: /usr/bin/test -e /usr/lib64/php/modules/uploadprogress.so
  register: uploadprogress_exists
  ignore_errors: True

- name:  uploadprogress | install PHP module uploadprogress
  shell: pecl install uploadprogress
  when: uploadprogress_exists|failed
  
- name:  xdebug | test xdebug exists
  command: /usr/bin/test -e /usr/lib64/php/modules/xdebug.so
  register: xdebug_exists
  ignore_errors: True

- name:  xdebug | install PHP module Xdebug
  shell: pecl install Xdebug
  when: xdebug_exists|failed

- name:  xdebug | copy xdebug.ini
  template: src=xdebug.ini dest=/etc/php.d/xdebug.ini
  notify:
    - restart apache
