---
- name: Test the existence of drush
  command: /usr/bin/drush
  register: drush_existence
  ignore_errors: True
  
- name: Add drush via PEAR channel
  shell: pear channel-discover pear.drush.org || true
  when: drush_existence|failed
  
- name: Install Console_Table as a drush dependency
  shell: pear install Console_Table
  when: drush_existence|failed
  
- name: Install drush
  shell: pear install -f drush/drush
  when: drush_existence|failed
  
- name: Clone portal-drupal7 repository
  git: repo={{ drupal_repo }}
       dest={{ drupal_core_path }}

- name: Proper permission for Drupal files
  file: path={{ drupal_core_path }} state=directory owner=apache group=apache mode=0755 recurse=yes

- name: Proper permission for Drupal site files
  file: path={{ drupal_core_path }}/sites/default state=directory owner=apache group=apache mode=0775

- name: Install virtual host
  template: src=virt_portal.conf dest=/etc/httpd/conf.d/virt_portal.conf
  notify:
    - restart apache

- name: Create a new database for Drupal
  mysql_db: name={{ drupal_mysql_db }} state=present encoding=utf8 collation=utf8_general_ci

# @see http://stackoverflow.com/questions/22958443/how-to-grant-mysql-server-administration-privileges-super-reload-with-ansi  
- name: Create a MySQL user for Drupal
  mysql_user: name={{ drupal_mysql_user }} password={{ drupal_mysql_passwd }} priv={{ drupal_mysql_privileges }} state=present

- name: Test the existence of drush
  command: /usr/bin/test -e {{ drupal_core_path }}/sites/default/settings.php
  register: drupal_setting_exists
  ignore_errors: True
  
- name: Creating settings.php
  template: src=settings.php dest={{ drupal_core_path }}/sites/default/settings.php owner=apache group=apache mode=0775
  when: drupal_setting_exists|failed
  
- name: Install Drupal using standard profile
  shell: chdir={{ drupal_core_path }}/sites/default drush site-install standard -y
  sudo: yes
  sudo_user: apache
  