---
# This is an example of settings.yml. Make a copy of this file and rename it as
# settings.yml for the settings to take effect.

# Roles switch
  xhprof: "Y"
  xhprof_ui: "ui" # Choose 'ui' to use the one from Facebook, 'io' to use a better-looking but pre-release one.

# System settings
  project_machine_name: 'centos_drupal'
  staging_env: 'dev' # 'dev', 'uat', or '' for PROD.
  box_os: 'centos'
  box_ip_address: '10.1.1.3'
  box_ram: 2048

# Apache settings
  http_port: 80
  http_ServerAdmin: 'root@localhost'
  apache_create_vhosts: false
  http_base: "/var/www"
  
# php.ini settings
  php_memory_limit: 512M
  php_max_input_time: 60
  php_max_execution_time: 300
  php_post_max_size: 8M
  php_upload_max_filesize: 2M
  php_display_errors: On
  php_display_startup_errors: On
  php_html_errors: On
  php_date_timezone: Europe/Copenhagen
  php_default_latitude: 55.7022
  php_default_longitude: 12.5592

# PHP APC settings  
  apc_rfc1867: '1'
  apc_shm_size: '256M'
  apc_shm_segments: '1'
  apc_num_files_hint: '0'
  
# PHP XDebug settings
  php_xdebug_remote_enable: 1
  
# PHP XHProf settings
  php_xhprof_doc_base: xhgui
  php_xhprof_prepend: "/var/www/{{ php_xhprof_doc_base }}/external/header.php"
  php_xhprof_ServerName: "{{ php_xhprof_doc_base }}.{{ box_os }}-{{ staging_env }}.local"

# MySQL settings  
  mysql_root_passwd: rootpassword
  mysql_port: 3306
  mysql_admin_user: cent
  mysql_admin_passwd: centpwd
  mysql_admin_privileges: "*.*:ALL,GRANT"
  mysql_admin_allowed_host: "%"

# MySQL my.cnf settings
  mysql_max_allowed_packet: 128M
  innodb_file_per_table: 1
  mysql_character_set_server: utf8
  mysql_collation_server: utf8_general_ci
  
# Drupal settings
  drupal_core_version: "7"
  drupal_current_version: "28"
  drupal_core_path: "/var/www/d{{ drupal_core_version }}"
  drupal_domain: "d7.centos-{{ staging_env }}.local"
  drupal_site_name: "GBIF Drupal {{ staging_env }}"
  drupal_repo: "https://github.com/gbif/gbif-drupal.git"
  drupal_apache_access_log: "logs/gbif-drupal-access_log"
  drupal_apache_error_log: "logs/gbif-drupal-error_log"
  drupal_mysql_db: "gbif_drupal"
  drupal_mysql_privileges: "{{ drupal_mysql_db }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX,ALTER,'CREATE TEMPORARY TABLES'"
  drupal_mysql_user: "gbif_drupal"
  drupal_mysql_passwd: "gbif_drupal"
  drupal_mysql_host: "localhost"

  drupal_user_0: admin
  drupal_user_0_passwd: password
  drush_version: master

  data_portal_base_url: "http://www.gbif-{{ staging_env }}.org"
  gbif_api_base_url: "http://api.gbif-{{ staging_env }}.org"
  gbif_api_version: "0.9"

  gbif_ims_host: "filemakerurl" # No protocol needed here.
  gbif_ims_db: "imsdbname"
  gbif_ims_user: "ims_user"
  gbif_ims_passwd: "ims_passwd"