---
# This is an example of settings.yml. Make a copy of this file and rename it as
# settings.yml for the settings to take effect.
  
# System settings
  project_machine_name: 'centos_drupal'
  staging_env: 'dev'
  box_os: 'centos'
  box_ip_address: '10.1.1.3'

# Apache settings
  http_port: 80
  http_ServerAdmin: 'root@localhost'
  apache_create_vhosts: false
  
# php.ini settings
  php_memory_limit: 512M
  php_max_input_time: 60
  php_max_execution_time: 300
  php_post_max_size: 8M
  php_upload_max_filesize: 2M
  php_display_errors: On
  php_display_startup_errors: On
  php_html_errors: On
  php_date_timezone: Europe/Copenhagen
  php_default_latitude: 55.7022
  php_default_longitude: 12.5592
  php_error_reporting: "E_ALL & ~E_DEPRECATED"

# PHP APC settings  
  apc_rfc1867: '1'
  apc_shm_size: '256M'
  apc_shm_segments: '1'
  apc_num_files_hint: '0'
  
# PHP XDebug settings
  php_xdebug_remote_enable: 1

# MySQL settings  
  mysql_root_passwd: rootpassword
  mysql_port: 3306

# MySQL my.cnf settings
  mysql_max_allowed_packet: 128M
  innodb_file_per_table: 1
  mysql_character_set_server: utf8
  mysql_collation_server: utf8_general_ci
  
# Drupal settings
  drupal_core_version: "7"
  drupal_core_path: "/var/www/d{{ drupal_core_version }}"
  drupal_domain: "d7.centos-{{ staging_env }}.local"
  drupal_site_name: "GBIF Drupal {{ staging_env }}"
  drupal_repo: "https://github.com/burkeker/portal-drupal7.git"
  drupal_apache_access_log: "logs/portal-drupal7-access_log"
  drupal_apache_error_log: "logs/portal-drupal7-error_log"
  drupal_mysql_db: "portal_drupal7"
  drupal_mysql_privileges: "{{ drupal_mysql_db }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX,ALTER,'CREATE TEMPORARY TABLES'"
  drupal_mysql_user: "portal_drupal7"
  drupal_mysql_passwd: "portal_drupal7"
  drupal_mysql_host: "localhost"

  drush_version: master

  data_portal_base_url: "http://www.gbif-{{ staging_env }}.org"
  gbif_api_base_url: "http://api.gbif-{{ staging_env }}.org"
  gbif_api_version: "0.9"

  gbif_ims_host: "filemaker.gbif.org" # No protocol needed here.
  gbif_ims_db: "IMS_NG"
  gbif_ims_user: "ims_user"
  gbif_ims_passwd: "ims_passwd"