---
# Simple Drupal Development VM Playbook for CentOS 6.5
#
# This playbook will install Drupal on a CentOS-based LAMP stack and configure
# a profiling and debugging environment.
#
# @see http://labs.qandidate.com/blog/2013/11/21/installing-a-lamp-server-with-ansible-playbooks-and-roles/
# @see http://www.slideshare.net/geerlingguy/local-development-on-virtual-machines-vagrant-virtualbox-and-ansible
#
# @author Burke Chih-Jen Ko, 2014

- hosts: all
  vars_files:
    - settings.yml
  roles:
    - system
    - apache
    - php
    - memcached
    - mysql
    - drupal
