---
# Simple Drupal Development VM Playbook for CentOS 6.5
#
# This playbook will install Drupal on an CentOS-based LAMP stack for the development
# of the web layer of GBIF.
#
# @author Burke Chih-Jen Ko, 2014

 - hosts: all
   

   handlers:

   - name: restart iptables
     service: name=iptables state=restarted

   - name: restart httpd
     service: name=httpd state=restarted

   tasks: 

   - name: copy firewall template
     copy: src=templates/etc/sysconfig/iptables dest=/etc/sysconfig/iptables owner=root group=root mode=0600
     notify: restart iptables

   - name: Install http and php etc
     yum: pkg={{ item }} state=installed
     with_items:
        - httpd
        - php
        - php-common
        - php-xml
        - php-mysql
        - php-gd
        - php-tidy
        - php-pear

   - name: Ensure Apache running
     service: name=httpd state=started enabled=yes