---
- name: test if xhprof exists
  command: /usr/bin/test -e /usr/lib64/php/modules/xhprof.so
  register: xhprof_exists
  ignore_errors: True

- name: set preferred_state for pear
  command: pecl config-set preferred_state beta
  when: xhprof_exists|failed

- name: install xhprof
  command: pecl install xhprof
  when: xhprof_exists|failed

- name:  remove redundent line
  lineinfile: dest=/etc/php.ini line="extension=\"xhprof.so\"" state=absent

- name: test whether /tmp/xhprof exists
  command: /usr/bin/test -e /tmp/xhprof
  register: xhprof_tmp_exists
  ignore_errors: True

- name: create xhprof output file
  command: "{{ item }}"
  with_items:
    - mkdir /tmp/xhprof
    - chmod 777 /tmp/xhprof
  when: xhprof_tmp_exists|failed

- name: copy xhprof.ini
  template: src=xhprof.ini dest=/etc/php.d/xhprof.ini
  notify:
    - restart apache